# Author
hangar: https://hangar.papermc.io/AmokDev/DeathNote
github: https://github.com/AmokDev/DeathNote

# /kira Command Cooldown (In Seconds) | 1 hour is 3600 seconds | 1 minute is 60 seconds |
kira_cooldown: 3600








# Console Gradient Color Type
_translation:
  _commands:
    kills: 
      - '§7List of causes of death'
      - ' • lightning - lightning strike'
      - ' • guardian - murder by guard'
      - ''
    kira:
      wait_another: '§7Wait another'
  _events:
    give_death_note:
      death_note_picked_up: '§7You picked up the Death Note!'
    write_victim:
      not_enough_rights: '§7You do not have enough rights to use Death Note!'
      incorrect_input: '§7Invalid input! Example - "Name by lightning"'
      victim_offline: '§7Your target is offline!'
      inaccessible_game_mode: '§7The player is in a game mode inaccessible to the Death Note!'
      cant_find_a_way_of_death: '§7I couldn`t find a suitable way to die in my piggy bank! Try to find something you need using the /kills command'
  _deaths:
    name_color: '§4'
    murderer_color: '§e'
    was_killed_by: '§7was killed by'
    murders:
      lightning: 'lightning'
      guardian: 'guardian'
  _other:
    tag: '§7Death Note §8>>'
    config_restarted: '§7Config reloaded!' # /kira reload
    inventory_command_kira_name: '§x§8§7§0§0§0§0K§x§5§8§0§0§0§0i§x§5§8§0§0§0§0r§x§8§7§0§0§0§0a'
    death_note_name: '§x§5§3§0§0§0§0§lD§x§3§8§1§9§1§9§le§x§2§9§2§9§2§9§la§x§2§c§2§c§2§c§lt§x§3§9§1§7§1§7§lh §x§4§2§0§0§0§0§lN§x§3§0§0§0§0§0§lo§x§2§b§1§2§1§2§lt§x§2§f§2§f§2§f§le'
    days: 'd'
    hours: 'h'
    minutes: 'm'
    seconds: 's'

